### ISSUE TITLE
Lack of customisable convergence criterion

### ISSUE THREAD

**Issue by charles-cunningham** [inlabru-org/inlabru#51]
It would be useful to have a customisable stopping criterion, aside from the bru option max.iter. For example, being able to change the fixed 1% stopping criterion to 2% etc.

**Comment by finnlindgren** [comment]
This is now available (at least in the devel version; has been there under a different name before, but I'm not sure from when) as the `rel_tol` suboption to `bru_method`, and can be set via `options=list(bru_method=list(rel_tol = 0.01))` (this is the default, with stopping criterion `max(abs(new-old)/sd) < rel_tol`)
