### ISSUE TITLE
Storing convergence information within bru object in user-friendly way

### ISSUE THREAD

**Issue by charles-cunningham** [inlabru-org/inlabru#52]
Convergence tracking information is currently stored in bru object ( fit$iinla$track) in an inconvenient format. This could potentially be changed to a more practical format for users wanting to gain information on model convergence.

**Comment by finnlindgren** [comment]
There is now a function to _plot_ convergence diagnostics in a relatively friendly way:
```r
fit <- bru(...)
bru_convergence_plot(fit)
```

**Comment by finnlindgren** [comment]
The tracking info is now stored in `fit$bru_iinla$track` in a "tidy" format, and `bru_convergence_plot(fit)` has been improved.
